# LLM
LLM_PROVIDER = "ollama"
OLLAMA_HOST = "http://localhost:11434"
OLLAMA_MODEL = "llama3:8b"

# Embedding model
EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"

# Snowflake connection
SNOWFLAKE_ACCOUNT = "WNUWVAA-IQ74328"
SNOWFLAKE_USER = "ANURAG001"
SNOWFLAKE_PASSWORD = "Anurag@200212Lanjewar"
SNOWFLAKE_WAREHOUSE = "COMPUTE_WH"
